# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# # Autor: Blas Morales Palacios
# Correo electrónico: amoralesp98@gmail.com
# Descripción: La herramienta SNAP estándar alinea todos los puntos al polígono más cercano, 
#              sin considerar relaciones específicas. 
#              Este script resuelve esta limitación al iterar sobre cada polígono, 
#              identificar los puntos asociados mediante un campo de interés y alinear solo esos puntos
#              a su polígono correspondiente, 
#              logrando una alineación más precisa y relevante
# Instrucciones de uso: python verificar_urls.py urls.txt
# Created on: 2025-02-16 03:28:52.00000
#   (generated by ArcGIS/ModelBuilder)

# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
BLOCK = arcpy.GetParameterAsText(0)
if BLOCK == '#' or not BLOCK:
    BLOCK = "BLOCK" # provide a default value if unspecified

POINT = arcpy.GetParameterAsText(1)
if POINT == '#' or not POINT:
    POINT = "POINT" # provide a default value if unspecified

# Local variables:
I_BLOCK = BLOCK
Value = "1"
ID_BLOCK = I_BLOCK
POINT_SNAP = I_BLOCK
POINT_SELECT = POINT

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(BLOCK, "BLOCK #", "false")

# Process: Get Field Value
arcpy.GetFieldValue_mb(I_BLOCK, "BLOCK", "String", "")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(POINT, "NEW_SELECTION", "BLOCK = '%ID_BLOCK%'")

# Process: Snap
arcpy.Snap_edit(POINT_SELECT, "I_BLOCK_BLOCK EDGE '15 Unknown'")

