# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Autor: Blas Morales Palacios
# Correo electrónico: amoralesp98@gmail.com
# Descripción: Este script hace una alineación autimatica del punto a un poligono tomando en cuenta un campo en comun.
# Instrucciones de uso: python verificar_urls.py urls.txt
# Created on: 2025-02-16 03:28:52.00000
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Manzana = arcpy.GetParameterAsText(0)
if Manzana == '#' or not Manzana:
    Manzana = "Manzana" # provide a default value if unspecified

Lote_snap = arcpy.GetParameterAsText(1)
if Lote_snap == '#' or not Lote_snap:
    Lote_snap = "Lote_snap" # provide a default value if unspecified

# Local variables:
I_Manzana = Manzana
Value = "1"
MZMUNI = I_Manzana
Lote_snap__4_ = I_Manzana
Lote_snap__3_ = Lote_snap

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(Manzana, "", "false")

# Process: Get Field Value
arcpy.GetFieldValue_mb(I_Manzana, "MZMUNI", "String", "")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Lote_snap, "NEW_SELECTION", "MZMUNI = '%MZMUNI%'")

# Process: Snap
arcpy.Snap_edit(Lote_snap__3_, "I_Manzana EDGE '15 Unknown'")

